# postgres-stm-deployment.yml
---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-stm
  namespace: fais-1
  labels:
    app: postgres-stm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-stm
  template:
    metadata:
      labels:
        app: postgres-stm
    spec:
      securityContext:
        runAsUser: 270999
        runAsGroup: 50038
        fsGroup: 1134
      containers:
      - name: postgres
        image: postgis/postgis:16-3.4  # Using PostGIS based on PostgreSQL 16
        env:
        - name: POSTGRES_USER
          value: "forum_user"
        - name: POSTGRES_PASSWORD
          value: "forum_password"
        - name: POSTGRES_DB
          value: "forum_db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        nfs:
          server: 128.239.59.144
          path: /sciclone/geograd/stmorse/chs/autogen-forum/db

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-stm-service
  namespace: fais-1
spec:
  selector:
    app: postgres-stm
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP