apiVersion: v1
kind: Pod
metadata:
  name: forum
  namespace: fais-1
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 50038
    fsGroup: 1134
  containers:
  - name: forum-container
    image: ghcr.io/stmorse/autogen-forum:latest
    resources:
      requests:
        memory: '4Gi'
        cpu: '1'
    command: ['/bin/bash', '-c', 'sleep infinity']
    volumeMounts:
    - name: code-volume
      mountPath: /app
  volumes:
  - name: code-volume
    nfs:
      server: 128.239.59.144
      path: /sciclone/geograd/stmorse/chs/autogen-forum